package initialPackages.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import initialPackages.WhitelistRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/mobile-api") // This means URL's start with /demo (after Application path)
public class MobileAPIController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private WhitelistRepository whitelistRepository;


	@GetMapping(path = "/verify-email")
	public @ResponseBody boolean verifyEmail(@RequestParam String email){

		return whitelistRepository.existsById(email);
	}

}
